kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: production
  name: production-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 