apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: okta-kubectl-blog-eksctl
  region: {AWS_REGION}

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  iam:
    withAddonPolicies:
      albIngress: true
